# A股推荐系统配置文件

# 全局配置
global:
  # 是否启用各模型模块
  enable_modules:
    rule_model: true     # 规则模型
    ml_model: true       # 机器学习模型
    llm_model: true      # 大语言模型
    fusion: true         # 融合模块
  # 推荐股票数量
  top_n: 10
  # 日志级别
  log_level: "INFO"
  # 输出目录
  output_dir: "./output"

# 数据源配置
data_source:
  type: "akshare"  # 使用AKShare作为数据源
  # AKShare配置
  provider: "akshare"
  # 数据开始日期
  start_date: "20230101"
  # 数据结束日期
  end_date: "20231231"
  # 股票池（为空时自动获取全部A股）
  stock_pool: []
  # 指数池
  index_pool: ["sh000001", "sz399001", "sz399006"]
  # 数据缓存目录
  cache_dir: "./data/cache"
  # AKShare特定配置
  akshare:
    # 复权方式: qfq(前复权), hfq(后复权), none(不复权)
    adjust: "qfq"
    # 数据周期: daily, weekly, monthly
    period: "daily"
    # 请求延时(秒)，避免请求过快
    request_delay: 0.2
    # 重试次数
    retry_times: 3
    # 重试延时(秒)
    retry_delay: 1

# 特征工程配置
features:
  # 技术指标
  technical_indicators:
    - "ma"      # 移动平均线
    - "ema"     # 指数移动平均线
    - "macd"    # MACD指标
    - "rsi"     # 相对强弱指数
    - "kdj"     # KDJ指标
    - "boll"    # 布林带
    - "atr"     # 真实波动幅度
    - "obv"     # 能量潮
    - "roc"     # 变动率
    - "cci"     # 顺势指标
  # 基本面指标
  fundamental_indicators:
    - "pe"      # 市盈率
    - "pb"      # 市净率
    - "roe"     # 净资产收益率
    - "revenue_growth"  # 营收增长率
  # 特征选择方法: correlation, mutual_info, rfe, lasso
  selection_method: "mutual_info"
  # 选择的特征数量
  top_n_features: 20

# 机器学习模型配置
model:
  # 模型类型: xgboost, lightgbm, catboost, lstm, ensemble
  type: "xgboost"
  # 模型参数
  params:
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 100
    subsample: 0.8
    colsample_bytree: 0.8
  # 训练测试集划分比例
  train_test_split: 0.8
  # 交叉验证折数
  cv_folds: 5
  # 目标变量
  target_variable: "next_day_return"
  # 模型保存路径
  model_save_path: "./models/xgboost_model.pkl"

# 规则模型配置
rule_model:
  # 技术指标权重
  weights:
    ma_cross: 0.2
    macd: 0.2
    rsi: 0.15
    kdj: 0.15
    boll: 0.15
    volume: 0.15
  # 指标阈值
  thresholds:
    rsi_oversold: 30
    rsi_overbought: 70
    kdj_oversold: 20
    kdj_overbought: 80

# 大语言模型配置
llm:
  # API密钥
  api_key: "your_openai_api_key_here"
  # 模型名称
  model_name: "gpt-3.5-turbo"
  # 新闻来源
  news_sources:
    - "eastmoney"
    - "sina_finance"
    - "netease_finance"
    - "weibo_hot"
  # 最大token数
  max_tokens: 1000
  # 温度参数
  temperature: 0.7
  # 缓存目录
  cache_dir: "./data/llm_cache"

# 评分融合配置
score_fusion:
  # 融合策略: weighted_average, geometric_mean, harmonic_mean, max, min
  fusion_strategy: "weighted_average"
  # 各模型权重
  weights:
    ml_model: 0.4
    rule_model: 0.3
    llm_model: 0.3
  # 评分范围
  score_range: [0.0, 1.0]
  # 是否启用归一化
  enable_normalization: true

# 策略配置
strategy:
  # 最大持仓数量
  max_positions: 10
  # 仓位大小策略: equal, market_cap, volatility, score
  position_sizing: "score"
  # 行业分散化
  sector_diversification: true
  # 风险控制规则
  risk_rules:
    max_sector_exposure: 0.3
    max_single_position: 0.15
    min_liquidity: 10000000

# 回测配置
backtest:
  # 初始资金
  initial_capital: 1000000
  # 手续费率
  commission_rate: 0.0003
  # 滑点
  slippage: 0.0002
  # 基准指数
  benchmark: "sh000001"
  # 调仓频率: daily, weekly, monthly
  rebalance_frequency: "weekly"
  # 无风险利率
  risk_free_rate: 0.03

# 日志配置
logging:
  # 日志级别
  level: "INFO"
  # 日志目录
  log_dir: "./logs"
  # 是否输出到控制台
  console_output: true
  # 日志文件大小限制(MB)
  file_size_limit: 10
  # 备份数量
  backup_count: 5

# 输出配置
output:
  # 报告目录
  report_dir: "./reports"
  # 是否生成图表
  plot_results: true
  # 是否导出CSV
  export_csv: true
  # 是否生成HTML报告
  generate_html: true