# 股票推荐系统因子配置文件
# 可以通过修改此文件来调整各因子的权重

factor_weights:
  # 动量因子权重 (总权重: 0.35)
  momentum_5d: 0.10      # 5日动量
  momentum_10d: 0.10     # 10日动量
  momentum_20d: 0.10     # 20日动量
  rsi: 0.05              # RSI指标
  
  # 成交量因子权重 (总权重: 0.20)
  volume_ratio: 0.08     # 成交量比率
  volume_spike: 0.07     # 成交量突增
  turnover_rate: 0.05    # 换手率
  
  # 资金流向因子权重 (总权重: 0.20)
  main_inflow_score: 0.10    # 主力资金净流入评分
  large_inflow_score: 0.05   # 大单资金净流入评分
  capital_strength: 0.05     # 综合资金强度
  
  # 技术指标权重 (总权重: 0.08)
  macd: 0.05             # MACD指标
  bollinger_position: 0.03   # 布林带位置
  
  # 情绪因子权重 (总权重: 0.17)
  news_sentiment_score: 0.08     # 新闻情绪评分
  market_sentiment_score: 0.04   # 市场情绪评分
  overall_sentiment: 0.05        # 综合情绪评分
  
  # 风险因子权重 (总权重: -0.02，负权重表示风险)
  volatility_20d: -0.05      # 20日波动率（负权重）
  price_stability: 0.03      # 价格稳定性
  
  # 其他因子
  change_pct: 0.02          # 当日涨跌幅

# 推荐系统配置
recommendation_config:
  # 基本筛选条件
  min_price: 3.0            # 最低价格
  max_price: 200.0          # 最高价格
  min_market_cap: 50        # 最小市值（亿元）
  max_pe_ratio: 100         # 最大市盈率
  
  # 推荐数量
  top_recommendations: 20   # 推荐股票数量
  
  # 风险控制
  max_single_stock_weight: 0.1  # 单只股票最大权重
  sector_diversification: true  # 是否进行行业分散
  
# 卖出决策配置
sell_config:
  # 止盈止损设置
  profit_threshold: 3.0     # 止盈阈值（%）
  loss_threshold: -3.0      # 止损阈值（%）
  
  # 持有期限制
  max_hold_days: 5          # 最大持有天数
  
  # 技术面检查
  technical_check: true     # 是否进行技术面检查
  volume_check: true        # 是否检查成交量异常
  
  # 仓位管理
  profit_taking_ratio: 0.5  # 盈利5%以上时的减仓比例
  risk_reduction_ratio: 0.3 # 亏损1.5%以上时的减仓比例

# 数据源配置
data_config:
  # 数据获取设置
  max_retry_times: 3        # 最大重试次数
  request_delay: 0.1        # 请求间隔（秒）
  
  # 历史数据天数
  history_days: 30          # 获取历史数据天数
  
  # 缓存设置
  enable_cache: true        # 是否启用缓存
  cache_expire_minutes: 30  # 缓存过期时间（分钟）

# 日志配置
log_config:
  level: "INFO"             # 日志级别
  file_path: "stock_recommendation.log"  # 日志文件路径
  max_file_size: 10         # 最大文件大小（MB）
  backup_count: 5           # 备份文件数量

# 通知配置（可选）
notification_config:
  enable_email: false       # 是否启用邮件通知
  enable_wechat: false      # 是否启用微信通知
  
  # 邮件设置
  email:
    smtp_server: "smtp.qq.com"
    smtp_port: 587
    username: "your_email@qq.com"
    password: "your_password"
    recipients: ["recipient@qq.com"]
  
  # 微信设置（企业微信机器人）
  wechat:
    webhook_url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=your_key"

# 回测配置
backtest_config:
  # 回测时间范围
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  
  # 初始资金
  initial_capital: 100000   # 初始资金（元）
  
  # 交易费用
  commission_rate: 0.0003   # 佣金费率
  stamp_tax_rate: 0.001     # 印花税费率
  
  # 风险指标
  benchmark: "000300"       # 基准指数（沪深300）