# 推荐系统融合策略配置文件

# 融合策略配置
fusion_strategy:
  # 融合方法: weighted_average(加权平均), filter_first(优先过滤), rank_adjustment(排序微调), consensus_boost(一致性增强)
  method: "consensus_boost"
  
  # 权重配置
  weights:
    ml_weight: 0.4          # 机器学习模型权重
    factor_weight: 0.6      # 多因子模型权重
    volume_weight: 0.1      # 成交量因子权重
    momentum_weight: 0.1    # 动量因子权重
    sentiment_weight: 0.05  # 情绪因子权重
  
  # 阈值配置
  thresholds:
    ml_threshold: 0.6       # ML预测概率阈值（用于过滤策略）
    factor_threshold: 0.5   # 因子得分阈值
    confidence_threshold: 0.7  # 高置信度阈值
    risk_threshold: 0.3     # 低风险阈值
    consensus_threshold: 0.8   # 一致性阈值
  
  # 一致性增强配置
  consensus_boost:
    max_bonus: 0.2          # 最大一致性加分比例
    min_strength: 0.1       # 最小信号强度要求
    penalty_factor: 0.1     # 分歧惩罚因子
  
  # 排序微调参数
  adjustment_factor: 2.0  # 排序调整系数(用于rank_adjustment方法)

# 输出配置
output:
  top_recommendations: 10  # Top N推荐数量
  output_dir: "result"   # 输出目录
  save_format: "json"     # 保存格式
  include_details: true   # 是否包含详细信息
  
  # 字段配置
  fields:
    required_fields:        # 必需字段
      - "rank"
      - "stock_code"
      - "stock_name"
      - "final_score"
      - "ml_probability"
      - "factor_score"
      - "recommendation_reason"
    
    optional_fields:        # 可选字段
      - "current_price"
      - "change_pct"
      - "confidence_level"
      - "risk_level"
      - "score_details"
      - "timestamp"
  
  # 推荐理由模板
  reason_templates:
    high_confidence: "ML预测概率{ml_prob:.1%}，因子得分{factor_score:.2f}，双重信号强烈看好"
    medium_confidence: "ML预测概率{ml_prob:.1%}，因子得分{factor_score:.2f}，综合表现良好"
    low_confidence: "ML预测概率{ml_prob:.1%}，因子得分{factor_score:.2f}，谨慎关注"
    consensus: "ML与因子模型高度一致，预测{direction}，置信度{confidence}"
    divergence: "ML与因子模型存在分歧，需要进一步观察"

# 股票池配置
stock_universe:
  # 默认股票池
  default:
    - "000001"  # 平安银行
    - "000002"  # 万科A
    - "000858"  # 五粮液
    - "000876"  # 新希望
    - "002415"  # 海康威视
    - "600000"  # 浦发银行
    - "600036"  # 招商银行
    - "600519"  # 贵州茅台
    - "600887"  # 伊利股份
    - "601318"  # 中国平安
    - "601398"  # 工商银行
    - "601857"  # 中国石油
    - "000858"  # 五粮液
    - "002304"  # 洋河股份
    - "600276"  # 恒瑞医药

# 风险控制配置
risk_control:
  # 推荐数量限制
  max_daily_recommendations: 20
  min_recommendations: 5
  
  # 风险分散配置
  sector_diversification:
    enabled: true
    max_per_sector: 3       # 每个行业最多推荐股票数
    min_sectors: 3          # 最少涉及行业数
  
  # 流动性要求
  liquidity_requirements:
    min_volume: 1000000     # 最小成交量（元）
    min_turnover_rate: 0.01 # 最小换手率
  
  # 波动率限制
  volatility_limits:
    max_volatility: 0.15    # 最大波动率
    volatility_window: 20   # 波动率计算窗口（天）

# 评分标准化配置
scoring_normalization:
  # ML概率标准化
  ml_probability:
    method: "minmax"        # minmax, zscore, sigmoid
    range: [0, 1]          # 标准化范围
  
  # 因子得分标准化
  factor_score:
    method: "minmax"
    range: [0, 1]
    clip_range: [-3, 3]    # 裁剪范围（标准化前）
  
  # 大盘蓝筹股票池
  blue_chip:
    - "600519"  # 贵州茅台
    - "000858"  # 五粮液
    - "601318"  # 中国平安
    - "600036"  # 招商银行
    - "000002"  # 万科A
    - "600276"  # 恒瑞医药
    - "600887"  # 伊利股份
    - "002415"  # 海康威视
    - "601398"  # 工商银行
    - "600000"  # 浦发银行
  
  # 成长股票池
  growth:
    - "002415"  # 海康威视
    - "000876"  # 新希望
    - "002304"  # 洋河股份
    - "600276"  # 恒瑞医药
    - "300059"  # 东方财富
    - "002142"  # 宁波银行
    - "000001"  # 平安银行
    - "600030"  # 中信证券
    - "000725"  # 京东方A
    - "002027"  # 分众传媒

# 风险控制配置
risk_control:
  max_single_stock_weight: 0.1    # 单只股票最大权重
  sector_concentration_limit: 0.3  # 行业集中度限制
  volatility_limit: 0.15          # 波动率限制
  liquidity_threshold: 1000000    # 流动性阈值(成交额)
  price_limit:
    min_price: 2.0                # 最低价格
    max_price: 1000.0             # 最高价格
  
  # 排除条件
  exclude_conditions:
    st_stocks: true               # 排除ST股票
    suspended_stocks: true        # 排除停牌股票
    new_stocks_days: 60          # 排除上市不足N天的新股

# 评分标准化配置
scoring_normalization:
  ml_score:
    method: "minmax"              # 标准化方法: minmax, zscore
    range: [0, 1]                # 目标范围
  
  factor_score:
    method: "minmax"
    range: [0, 1]
    outlier_treatment: "clip"     # 异常值处理: clip, remove

# 推荐理由生成配置
reason_generation:
  include_ml_confidence: true     # 包含ML置信度
  include_factor_breakdown: true  # 包含因子分解
  include_risk_warning: true      # 包含风险提示
  max_reason_length: 200         # 推荐理由最大长度

# 性能监控配置
performance_monitoring:
  enable_timing: true            # 启用性能计时
  log_level: "INFO"             # 日志级别
  save_intermediate_results: false # 保存中间结果

# 回测配置
backtest:
  enable: false                 # 是否启用回测
  lookback_days: 30            # 回测天数
  benchmark: "000300"          # 基准指数(沪深300)
  metrics:
    - "return"                 # 收益率
    - "sharpe_ratio"           # 夏普比率
    - "max_drawdown"           # 最大回撤
    - "win_rate"               # 胜率

# API配置
api_config:
  timeout: 30                   # API超时时间(秒)
  retry_times: 3               # 重试次数
  rate_limit: 100              # 速率限制(请求/分钟)

# 缓存配置
cache_config:
  enable: true                 # 启用缓存
  ttl: 3600                   # 缓存过期时间(秒)
  max_size: 1000              # 最大缓存条目数